-- Tournament referees: non-playing staff who can officiate matches

create table if not exists public.tournament_referees (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz default now(),
  unique(tournament_id, profile_id)
);

create index if not exists idx_tournament_referees_tournament on public.tournament_referees(tournament_id);
create index if not exists idx_tournament_referees_profile on public.tournament_referees(profile_id);

-- RLS for tournament referees
alter table public.tournament_referees enable row level security;

create policy "Tournament referees readable by everyone" on public.tournament_referees
  for select using (true);

create policy "Organizer can manage tournament referees" on public.tournament_referees
  for all using (
    exists (
      select 1 from public.tournaments t
      where t.id = tournament_id and t.organizer_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.tournaments t
      where t.id = tournament_id and t.organizer_id = auth.uid()
    )
  );

-- Per-match referee assignment (exactly one ref per match in v1)
alter table public.matches
  add column if not exists referee_profile_id uuid references public.profiles(id);

create index if not exists idx_matches_referee on public.matches(referee_profile_id);

-- Allow assigned referees to update their matches (alongside the existing organizer policy)
-- NOTE: This does not restrict which columns refs may update; the app should only
-- send score/status changes for referee-driven updates. We can harden this later
-- with a trigger if needed.
drop policy if exists matches_update_referee on public.matches;
create policy matches_update_referee
  on public.matches
  for update
  using (auth.uid() = referee_profile_id)
  with check (auth.uid() = referee_profile_id);
