-- Migration: Team Format Updates
-- 1. Change team size from fixed 6 to 6-10 players
-- 2. Change RD (Wildcard) to S (Singles) - different rules apply
-- 3. Singles slot only needs 1 player (not 2 like doubles)

-- ============================================================================
-- PART 1: Update slot_code constraint to use 'S' instead of 'RD'
-- ============================================================================

-- Drop the old constraint first
alter table public.entry_roster_slots 
  drop constraint if exists entry_roster_slots_slot_code_check;

-- Migrate existing RD data to S BEFORE adding new constraint
update public.entry_roster_slots set slot_code = 'S' where slot_code = 'RD';

-- Now add the new constraint
alter table public.entry_roster_slots 
  add constraint entry_roster_slots_slot_code_check 
  check (slot_code in ('MD', 'WD', 'XD', 'S'));

-- ============================================================================
-- PART 2: Update sub_match_type constraint on matches table
-- ============================================================================

alter table public.matches 
  drop constraint if exists matches_sub_match_type_check;

-- Migrate existing RD data to S BEFORE adding new constraint
update public.matches set sub_match_type = 'S' where sub_match_type = 'RD';

-- Now add the new constraint
alter table public.matches 
  add constraint matches_sub_match_type_check 
  check (sub_match_type in ('MD', 'WD', 'XD', 'S'));

-- ============================================================================
-- PART 3: Update roster validation function for new Singles rules
-- ============================================================================

-- Drop the old function and recreate with new rules
drop function if exists public.check_roster_constraints() cascade;

create or replace function public.check_roster_constraints()
returns trigger as $$
declare
  slot_count int;
  max_allowed int;
begin
  -- Determine max players per slot: Singles (S) = 1, Doubles (MD, WD, XD) = 2
  if NEW.slot_code = 'S' then
    max_allowed := 1;
  else
    max_allowed := 2;
  end if;

  -- Count existing players in this slot (excluding current row if UPDATE)
  if TG_OP = 'INSERT' then
    select count(*) into slot_count 
    from public.entry_roster_slots 
    where entry_id = NEW.entry_id and slot_code = NEW.slot_code;
  elsif TG_OP = 'UPDATE' then
    select count(*) into slot_count 
    from public.entry_roster_slots 
    where entry_id = NEW.entry_id and slot_code = NEW.slot_code and id != NEW.id;
  end if;

  -- Check if adding this player would exceed the limit
  if slot_count >= max_allowed then
    raise exception 'Cannot have more than % player(s) in % slot', max_allowed, NEW.slot_code;
  end if;

  -- Singles (S) has no special constraints like RD did
  -- Any team member can be assigned to Singles regardless of other assignments

  return NEW;
end;
$$ language plpgsql;

-- Recreate the trigger
drop trigger if exists check_roster_constraints_trigger on public.entry_roster_slots;

create trigger check_roster_constraints_trigger
  before insert or update on public.entry_roster_slots
  for each row execute function public.check_roster_constraints();

-- ============================================================================
-- PART 4: Add match_player_assignments table for captain-assigned lineups
-- ============================================================================

-- This table allows team captains to assign specific players to each sub-match
-- Players can be assigned to multiple matches (some play more than others)
create table if not exists public.match_player_assignments (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  entry_id bigint not null references public.entries(id) on delete cascade,
  profile_id uuid not null references public.profiles(id),
  position int not null check (position in (1, 2)), -- Player 1 or Player 2 (for doubles), just 1 for singles
  created_at timestamptz default now(),
  unique(match_id, entry_id, position) -- Each position per team per match is unique
);

create index if not exists idx_match_player_assignments_match on public.match_player_assignments(match_id);
create index if not exists idx_match_player_assignments_entry on public.match_player_assignments(entry_id);
create index if not exists idx_match_player_assignments_profile on public.match_player_assignments(profile_id);

-- RLS for match_player_assignments
alter table public.match_player_assignments enable row level security;

-- Everyone can read assignments
create policy "Match player assignments readable by everyone" 
  on public.match_player_assignments for select using (true);

-- Team captain (entry creator) can manage their team's assignments
create policy "Team captain can manage player assignments" 
  on public.match_player_assignments
  for all using (
    exists (
      select 1 from public.entries e 
      where e.id = entry_id and e.created_by = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.entries e 
      where e.id = entry_id and e.created_by = auth.uid()
    )
  );

-- Organizer can manage all assignments
create policy "Organizer can manage player assignments" 
  on public.match_player_assignments
  for all using (
    exists (
      select 1
      from public.matches m
      join public.tournament_categories tc on tc.id = m.category_id
      join public.tournaments t on t.id = tc.tournament_id
      where m.id = match_id and t.organizer_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.matches m
      join public.tournament_categories tc on tc.id = m.category_id
      join public.tournaments t on t.id = tc.tournament_id
      where m.id = match_id and t.organizer_id = auth.uid()
    )
  );

-- ============================================================================
-- PART 5: Add comment documenting team size expectations
-- ============================================================================

comment on column public.tournament_categories.members_per_team_min is 'Minimum team members required (default 6 for team format)';
comment on column public.tournament_categories.members_per_team_max is 'Maximum team members allowed (default 10 for team format)';
