-- Enums
create type entry_status as enum ('pending','accepted','waitlisted','withdrawn','rejected');
create type payment_status as enum ('unpaid','paid','refunded','waived');
create type bracket_type as enum ('single_elimination');
create type bracket_status as enum ('draft','active','completed','archived');
create type match_status as enum ('pending','scheduled','in_progress','completed','bye','walkover','cancelled');

-- Entries: one per team/singles registration in a category
create table if not exists public.entries (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.tournament_categories(id) on delete cascade,
  created_by uuid not null references public.profiles(id),
  team_name text,
  seed int,
  rating numeric(4,2),
  status entry_status not null default 'pending',
  payment_status payment_status not null default 'unpaid',
  payment_amount numeric(10,2),
  payment_currency text default 'usd',
  payment_reference text,
  paid_at timestamptz,
  created_at timestamptz default now()
);

-- Unique seed per category when present
create unique index if not exists entries_category_seed_unique on public.entries(category_id, seed) where seed is not null;
create index if not exists entries_category_idx on public.entries(category_id);
create index if not exists entries_created_by_idx on public.entries(created_by);

-- Entry members: link players to an entry (1 for singles, 2+ for doubles/teams)
create table if not exists public.entry_members (
  entry_id bigint not null references public.entries(id) on delete cascade,
  profile_id uuid not null references public.profiles(id),
  created_at timestamptz default now(),
  primary key (entry_id, profile_id)
);
create index if not exists entry_members_profile_idx on public.entry_members(profile_id);

-- Deprecated brackets/matches schema removed in favor of rounds/matches (20251027124500)

-- RLS
alter table public.entries enable row level security;
alter table public.entry_members enable row level security;
-- (deprecated) no RLS needed for removed tables

-- Public read access
drop policy if exists "Entries readable by everyone" on public.entries;
create policy "Entries readable by everyone" on public.entries for select using (true);

drop policy if exists "Entry members readable by everyone" on public.entry_members;
create policy "Entry members readable by everyone" on public.entry_members for select using (true);

-- (deprecated) removed public read policies for brackets/matches (legacy)

-- Entries: players can insert during registration window for categories in open tournaments
-- Organizer can insert too
drop policy if exists "Players can insert own entries during registration" on public.entries;
create policy "Players can insert own entries during registration" on public.entries
  for insert with check (
    auth.uid() = created_by and exists (
      select 1
      from public.tournament_categories tc
      join public.tournaments t on t.id = tc.tournament_id
      where tc.id = category_id
        and t.status = 'registration_open'
        and now() between t.registration_start_date and t.registration_end_date
    )
  );

drop policy if exists "Organizer can insert entries" on public.entries;
create policy "Organizer can insert entries" on public.entries
  for insert with check (
    exists (
      select 1 from public.tournament_categories tc
      join public.tournaments t on t.id = tc.tournament_id
      where tc.id = category_id and t.organizer_id = auth.uid()
    )
  );

-- Entries: participants can update only their own and only to safe statuses; organizer can update
drop policy if exists "Players can update own entries (safe)" on public.entries;
create policy "Players can update own entries (safe)" on public.entries
  for update using (created_by = auth.uid())
  with check (
    created_by = auth.uid() and status in ('pending','withdrawn')
  );

drop policy if exists "Organizer can update entries" on public.entries;
create policy "Organizer can update entries" on public.entries
  for update using (
    exists (
      select 1 from public.tournament_categories tc
      join public.tournaments t on t.id = tc.tournament_id
      where tc.id = category_id and t.organizer_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.tournament_categories tc
      join public.tournaments t on t.id = tc.tournament_id
      where tc.id = category_id and t.organizer_id = auth.uid()
    )
  );

-- Entries delete: players can delete own; organizer can delete
drop policy if exists "Players can delete own entries" on public.entries;
create policy "Players can delete own entries" on public.entries
  for delete using (created_by = auth.uid());

drop policy if exists "Organizer can delete entries" on public.entries;
create policy "Organizer can delete entries" on public.entries
  for delete using (
    exists (
      select 1 from public.tournament_categories tc
      join public.tournaments t on t.id = tc.tournament_id
      where tc.id = category_id and t.organizer_id = auth.uid()
    )
  );

-- Entry members: creator or organizer manages members
drop policy if exists "Players manage own entry members" on public.entry_members;
create policy "Players manage own entry members" on public.entry_members
  for all using (
    exists (
      select 1 from public.entries e where e.id = entry_id and e.created_by = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.entries e where e.id = entry_id and e.created_by = auth.uid()
    )
  );

drop policy if exists "Organizer manages entry members" on public.entry_members;
create policy "Organizer manages entry members" on public.entry_members
  for all using (
    exists (
      select 1
      from public.entries e
      join public.tournament_categories tc on tc.id = e.category_id
      join public.tournaments t on t.id = tc.tournament_id
      where e.id = entry_id and t.organizer_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.entries e
      join public.tournament_categories tc on tc.id = e.category_id
      join public.tournaments t on t.id = tc.tournament_id
      where e.id = entry_id and t.organizer_id = auth.uid()
    )
  );

-- (deprecated) removed organizer-only write policies for legacy brackets/matches
