-- Team Roster Slots: Maps players to specific roles within a team entry
-- Valid codes: MD (Men's Doubles), WD (Women's Doubles), XD (Mixed Doubles), RD (Reverse/Wildcard)
create table if not exists public.entry_roster_slots (
  id bigint generated by default as identity primary key,
  entry_id bigint not null references public.entries(id) on delete cascade,
  profile_id uuid not null references public.profiles(id),
  slot_code text not null check (slot_code in ('MD', 'WD', 'XD', 'RD')),
  created_at timestamptz default now(),
  unique(entry_id, profile_id, slot_code)
);

create index if not exists idx_entry_roster_slots_entry on public.entry_roster_slots(entry_id);
create index if not exists idx_entry_roster_slots_profile on public.entry_roster_slots(profile_id);

-- RLS for roster slots
alter table public.entry_roster_slots enable row level security;

create policy "Roster slots readable by everyone" on public.entry_roster_slots for select using (true);

create policy "Players can manage own roster slots" on public.entry_roster_slots
  for all using (
    exists (
      select 1 from public.entries e where e.id = entry_id and e.created_by = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.entries e where e.id = entry_id and e.created_by = auth.uid()
    )
  );

create policy "Organizer can manage roster slots" on public.entry_roster_slots
  for all using (
    exists (
      select 1
      from public.entries e
      join public.tournament_categories tc on tc.id = e.category_id
      join public.tournaments t on t.id = tc.tournament_id
      where e.id = entry_id and t.organizer_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.entries e
      join public.tournament_categories tc on tc.id = e.category_id
      join public.tournaments t on t.id = tc.tournament_id
      where e.id = entry_id and t.organizer_id = auth.uid()
    )
  );

-- Fixtures: High-level matchups between two teams (Entries)
-- This is the parent container for the 4 sub-matches
create table if not exists public.fixtures (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  category_id bigint not null references public.tournament_categories(id) on delete cascade,
  round_number int not null,
  entry1_id bigint references public.entries(id) on delete set null, -- Home Team
  entry2_id bigint references public.entries(id) on delete set null, -- Away Team
  status text not null default 'pending', -- scheduled, in_progress, completed
  created_at timestamptz default now()
);

create index if not exists idx_fixtures_category_round on public.fixtures(category_id, round_number);
create index if not exists idx_fixtures_entries on public.fixtures(entry1_id, entry2_id);

-- RLS for fixtures
alter table public.fixtures enable row level security;
create policy "Fixtures readable by everyone" on public.fixtures for select using (true);
create policy "Organizer can manage fixtures" on public.fixtures
  for all using (
    exists (
      select 1 from public.tournaments t where t.id = tournament_id and t.organizer_id = auth.uid()
    )
  );

-- Updates to Matches Table to link to Fixtures and track scores
alter table public.matches
  add column if not exists fixture_id bigint references public.fixtures(id) on delete cascade,
  add column if not exists sub_match_type text check (sub_match_type in ('MD', 'WD', 'XD', 'RD')),
  add column if not exists session_sequence int check (session_sequence in (1, 2)), -- 1=MD+WD, 2=XD+RD
  add column if not exists entry1_points int default 0,
  add column if not exists entry2_points int default 0;

create index if not exists idx_matches_fixture on public.matches(fixture_id);
